services:

  db:
    image: postgres:17-alpine
    container_name: postgresql-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    container_name: django_backend
    restart: always
    command: >
      /bin/sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - media_data:/app/media
      - static_data:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  daphne:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    container_name: django_daphne
    restart: always
    command: daphne -b 0.0.0.0 -p 8001 backend.asgi:application
    volumes:
      - ./backend:/app
      - media_data:/app/media
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    container_name: react_frontend
    restart: always
    working_dir: /app/frontend
    command: bun run dev --host 0.0.0.0
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "5173:5173"
    env_file:
      - .env
    depends_on:
      - backend

  celery:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    container_name: django_celery
    restart: always
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./backend:/app
      - media_data:/app/media
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data:
  media_data:
  static_data:
